import { UserProfile, KvkCenter, DiseaseDiagnosis, YieldPredictionResult, RegionalAlert, AdminActivityLog } from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user_admin_01',
    phone: '9876543210',
    name: 'Dr. V. K. Sharma (Sr. Scientist & Agronomist)',
    role: 'admin',
    language: 'hi',
    location: {
      state: 'Punjab',
      district: 'Ludhiana',
      lat: 30.9010,
      lng: 75.8573,
    },
    primaryCrops: ['Wheat', 'Rice', 'Mustard'],
    landSizeAcres: 15,
    soilType: 'Alluvial',
    notificationsEnabled: true,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'user_farmer_01',
    phone: '9988776655',
    name: 'Ramesh Patel',
    role: 'farmer',
    language: 'hi',
    location: {
      state: 'Gujarat',
      district: 'Anand',
      lat: 22.5645,
      lng: 72.9289,
    },
    primaryCrops: ['Cotton', 'Wheat', 'Groundnut'],
    landSizeAcres: 4.5,
    soilType: 'Black',
    notificationsEnabled: true,
    createdAt: '2026-02-10T11:30:00Z',
  },
  {
    id: 'user_farmer_02',
    phone: '9812345678',
    name: 'Balwinder Singh',
    role: 'farmer',
    language: 'pa',
    location: {
      state: 'Punjab',
      district: 'Ludhiana',
      lat: 30.8700,
      lng: 75.8200,
    },
    primaryCrops: ['Wheat', 'Paddy (Basmati)', 'Maize'],
    landSizeAcres: 8.0,
    soilType: 'Alluvial',
    notificationsEnabled: true,
    createdAt: '2026-02-14T14:15:00Z',
  },
  {
    id: 'user_farmer_03',
    phone: '9733445566',
    name: 'S. Murugan',
    role: 'farmer',
    language: 'ta',
    location: {
      state: 'Tamil Nadu',
      district: 'Thanjavur',
      lat: 10.7870,
      lng: 79.1378,
    },
    primaryCrops: ['Rice', 'Sugarcane', 'Black Gram'],
    landSizeAcres: 3.2,
    soilType: 'Clayey Loam',
    notificationsEnabled: true,
    createdAt: '2026-02-20T10:00:00Z',
  },
];

export const INITIAL_KVK_CENTERS: KvkCenter[] = [
  {
    id: 'kvk_01',
    name: 'ICAR - Krishi Vigyan Kendra, PAU Campus',
    type: 'KVK',
    state: 'Punjab',
    district: 'Ludhiana',
    address: 'Punjab Agricultural University Campus, Ferozepur Road, Ludhiana - 141004',
    phone: '+91 161 2401960',
    email: 'kvkludhiana@pau.edu',
    contactPerson: 'Dr. Gurmeet Singh (Programme Coordinator)',
    latitude: 30.9010,
    longitude: 75.8573,
    services: [
      'Soil & Water Testing Lab',
      'Certified Seed Sales (Wheat/Paddy)',
      'Plant Clinic & Disease Diagnosis',
      'Custom Hiring Center (Laser Leveller/Happy Seeder)',
      'Free On-Farm Advisory',
    ],
    operationalHours: 'Mon - Sat: 9:00 AM - 5:00 PM',
  },
  {
    id: 'kvk_02',
    name: 'Kisan Krishi Seva Kendra & Agro Input Hub',
    type: 'Krishi Seva Kendra',
    state: 'Punjab',
    district: 'Ludhiana',
    address: 'Near Old Grain Market, Samrala Chowk, Ludhiana - 141008',
    phone: '+91 98721 00112',
    contactPerson: 'Harpreet Singh Cheema',
    latitude: 30.9120,
    longitude: 75.8750,
    services: [
      'Subsidized Fertilizers (Urea/DAP/MOP)',
      'Bio-Pesticides & Neem Formulations',
      'Sprayer Equipment Rental',
      'Soil Health Card Guidance',
    ],
    operationalHours: 'All Days: 8:00 AM - 7:00 PM',
  },
  {
    id: 'kvk_03',
    name: 'ICAR - Krishi Vigyan Kendra, Anand Agricultural University',
    type: 'KVK',
    state: 'Gujarat',
    district: 'Anand',
    address: 'AAU Campus, B.A. College of Agriculture, Anand - 388110',
    phone: '+91 2692 261310',
    email: 'pc_kvkanand@aau.in',
    contactPerson: 'Dr. N. B. Chauhan',
    latitude: 22.5530,
    longitude: 72.9510,
    services: [
      'Comprehensive Soil Health Testing (N-P-K-Zn)',
      'Tissue Culture Banana & Fruit Saplings',
      'Integrated Pest Management (IPM) Kits',
      'Dairy & Animal Husbandry Guidance',
    ],
    operationalHours: 'Mon - Sat: 9:30 AM - 5:30 PM',
  },
  {
    id: 'kvk_04',
    name: 'ICAR - Central Institute for Cotton Research (CICR) KVK',
    type: 'KVK',
    state: 'Maharashtra',
    district: 'Nagpur',
    address: 'Post Bag No. 2, Shankarnagar Post, Wardha Road, Nagpur - 440010',
    phone: '+91 7103 275536',
    email: 'kvk.nagpur@icar.gov.in',
    contactPerson: 'Dr. U. V. Galkar',
    latitude: 21.0421,
    longitude: 79.0560,
    services: [
      'Cotton Bollworm Trap Kits (Pheromone)',
      'Soil Salinity & Alkalinity Remediation',
      'Drip Irrigation Subsidy Assistance',
      'Trichoderma Bio-agent Cultures',
    ],
    operationalHours: 'Mon - Fri: 9:00 AM - 5:30 PM',
  },
  {
    id: 'kvk_05',
    name: 'Tamil Nadu Agricultural University KVK, Needamangalam',
    type: 'KVK',
    state: 'Tamil Nadu',
    district: 'Thanjavur',
    address: 'Rice Research Station Campus, Needamangalam, Thanjavur - 614404',
    phone: '+91 4367 260666',
    email: 'kvkndm@tnau.ac.in',
    contactPerson: 'Dr. K. Ramasamy',
    latitude: 10.7712,
    longitude: 79.4215,
    services: [
      'Delta Paddy Disease Advisory',
      'Green Manure Seeds (Daincha/Sunhemp)',
      'Bio-Fertilizer Packets (Azospirillum/Phosphobacteria)',
      'Weather Forecast Advisory Service',
    ],
    operationalHours: 'Mon - Sat: 9:00 AM - 5:00 PM',
  },
  {
    id: 'kvk_06',
    name: 'ICAR - Indian Agricultural Research Institute (IARI) KVK Shikohpur',
    type: 'KVK',
    state: 'Haryana',
    district: 'Gurugram',
    address: 'Village Shikohpur, Near NH-48, Gurugram - 122004',
    phone: '+91 124 2265246',
    email: 'kvkshikohpur@iari.res.in',
    contactPerson: 'Dr. Anamika Sharma',
    latitude: 28.3750,
    longitude: 76.9800,
    services: [
      'Pusa Hydrogel Distribution',
      'Micro-Nutrient Foliar Spray Kits',
      'Protected Cultivation (Polyhouse) Training',
      'Organic Certification Support',
    ],
    operationalHours: 'Mon - Sat: 9:00 AM - 5:00 PM',
  },
  {
    id: 'kvk_07',
    name: 'Chandra Shekhar Azad University KVK, Kanpur Nagar',
    type: 'KVK',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    address: 'CSAUAT Campus, Rawatpur, Kanpur - 208002',
    phone: '+91 512 2534157',
    email: 'kvkkanpur@csauk.ac.in',
    contactPerson: 'Dr. Ashok Kumar Rai',
    latitude: 26.4950,
    longitude: 80.3080,
    services: [
      'Soil Testing & Micronutrient Analysis',
      'Pulse & Oilseed Demonstration Plots',
      'Beekeeping (Apiculture) Kits',
      'Weedicide & Herbicide Proper Dosage Guidance',
    ],
    operationalHours: 'Mon - Sat: 9:30 AM - 5:00 PM',
  },
];

export const INITIAL_DISEASE_SCANS: DiseaseDiagnosis[] = [
  {
    id: 'scan_001',
    farmerId: 'user_farmer_01',
    crop: 'Tomato',
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=600&q=80',
    diseaseDetected: 'Tomato Early Blight (Alternaria solani)',
    scientificName: 'Alternaria solani',
    confidence: 94.8,
    severity: 'high',
    recommendation: 'Remove infected lower leaves promptly to prevent spore splash. Spray fungicide early morning.',
    organicAlternative: 'Spray Trichoderma viride @ 5g/litre of water or Neem Seed Kernel Extract (NSKE 5%) weekly.',
    chemicalTreatment: 'Mancozeb 75% WP @ 2.5 g/L water or Chlorothalonil 75% WP @ 2 g/L water.',
    dosage: '500 grams in 200 Litres of water per acre.',
    timing: 'Early morning between 6:30 AM - 9:00 AM. Avoid spraying in direct harsh sunlight or imminent rain.',
    preventionTips: [
      'Practice crop rotation away from solanaceous crops (potato, brinjal) for at least 2 seasons.',
      'Use drip irrigation instead of overhead sprinklers to keep foliage dry.',
      'Maintain 60cm row spacing for good air circulation.',
    ],
    status: 'verified_by_admin',
    adminNotes: 'Confirmed by Dr. Sharma. Classical concentric ring target-spot lesions visible.',
    createdAt: '2026-03-20T10:15:00Z',
  },
  {
    id: 'scan_002',
    farmerId: 'user_farmer_01',
    crop: 'Cotton',
    imageUrl: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=600&q=80',
    diseaseDetected: 'Cotton Bacterial Blight / Angular Leaf Spot',
    scientificName: 'Xanthomonas citri pv. malvacearum',
    confidence: 76.5, // Below 85% threshold -> goes into Human-In-The-Loop review queue!
    severity: 'moderate',
    recommendation: 'Low-confidence detection flagged for human agronomist review. Isolate affected plants.',
    organicAlternative: 'Foliar spray of Pseudomonas fluorescens @ 10g/L water at 15-day intervals.',
    chemicalTreatment: 'Copper Oxychloride 50% WP (500g) + Streptocycline (20g) in 200L water per acre.',
    dosage: '2.5g Copper Oxychloride + 0.1g Streptocycline per Litre of water.',
    timing: 'Late afternoon after 4:00 PM.',
    preventionTips: [
      'Treat seeds with Carboxin 37.5% + Thiram 37.5% DS before sowing.',
      'Destroy crop residue after final picking.',
    ],
    status: 'under_review',
    createdAt: '2026-03-24T16:20:00Z',
  },
  {
    id: 'scan_003',
    farmerId: 'user_farmer_02',
    crop: 'Wheat',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    diseaseDetected: 'Wheat Yellow Stripe Rust (Puccinia striiformis)',
    scientificName: 'Puccinia striiformis f. sp. tritici',
    confidence: 96.2,
    severity: 'critical',
    recommendation: 'Critical danger for grain filling stage. Spray systemic fungicide across the entire block immediately.',
    organicAlternative: 'No effective bio-agent for acute stripe rust outbreak; immediate chemical intervention advised to avert 40% yield loss.',
    chemicalTreatment: 'Propiconazole 25% EC (Tilt) @ 1 ml/L water or Tebuconazole 25.9% EC @ 1 ml/L water.',
    dosage: '200 ml Tilt in 200 Litres of water per acre.',
    timing: 'Immediate calm morning spray with knapsack or tractor-mounted hollow cone nozzle.',
    preventionTips: [
      'Plant rust-resistant varieties like DBW 187, DBW 222, or PBW 725.',
      'Do not apply excessive urea/nitrogen when cloudy weather persists.',
    ],
    status: 'verified_by_admin',
    createdAt: '2026-03-22T08:45:00Z',
  },
  {
    id: 'scan_004',
    farmerId: 'user_farmer_03',
    crop: 'Rice',
    imageUrl: 'https://images.unsplash.com/photo-1536657464919-892534f60d6e?auto=format&fit=crop&w=600&q=80',
    diseaseDetected: 'Rice Blast (Magnaporthe oryzae)',
    scientificName: 'Magnaporthe oryzae',
    confidence: 79.4, // Below 85% threshold -> goes into review queue
    severity: 'high',
    recommendation: 'Spindle-shaped lesions with grey center detected on leaf blade. Flagged for verification.',
    organicAlternative: 'Foliar application of Neem oil 3000 ppm @ 3ml/L water.',
    chemicalTreatment: 'Tricyclazole 75% WP @ 0.6 g/L or Isoprothiolane 40% EC @ 1.5 ml/L water.',
    dosage: '120 grams Tricyclazole in 200 Litres water per acre.',
    timing: 'Early morning spray on still days.',
    preventionTips: [
      'Avoid excess nitrogen application in nursery and tillering stage.',
      'Drain water from flooded field for 24-48 hours if possible to reduce canopy humidity.',
    ],
    status: 'under_review',
    createdAt: '2026-03-25T11:10:00Z',
  },
];

export const INITIAL_YIELD_PREDICTIONS: YieldPredictionResult[] = [
  {
    id: 'yield_001',
    farmerId: 'user_farmer_01',
    crop: 'Wheat',
    soilType: 'Black',
    nitrogen: 130,
    phosphorus: 48,
    potassium: 160,
    ph: 7.4,
    areaAcres: 4.5,
    rainfallMm: 520,
    temperatureC: 24,
    irrigationType: 'Tube Well',
    predictedYieldPerAcreQuintals: 21.4,
    totalPredictedYieldQuintals: 96.3,
    confidenceScore: 91.5,
    districtBenchmarkQuintals: 18.2,
    yieldDeltaPercentage: 17.5, // 17.5% above benchmark!
    actionableTips: [
      'Apply Zinc Sulphate (21%) @ 10 kg/acre at 1st irrigation to prevent khaira/chlorosis in alkaline soil.',
      'Split nitrogen into 3 doses: 50% basal, 25% at CRI stage (21 days), and 25% at late tillering.',
      'Provide light irrigation at grain milk stage to safeguard test weight from sudden temperature rise.',
    ],
    createdAt: '2026-03-18T14:30:00Z',
  },
];

export const INITIAL_REGIONAL_ALERTS: RegionalAlert[] = [
  {
    id: 'alert_001',
    title: 'Yellow Stripe Rust Alert in Wheat',
    crop: 'Wheat',
    state: 'Punjab',
    district: 'Ludhiana',
    severity: 'critical',
    message: 'Cool and humid overcast conditions in Sub-Mountainous & Central Punjab have triggered initial foci of Yellow Rust. Inspect fields along water channels and tree shades.',
    actionRequired: 'If yellow powder rubs off on fingers from leaf stripes, spray Propiconazole 25% EC @ 200ml/acre immediately without delay.',
    broadcastDate: '2026-03-24T06:00:00Z',
    adminName: 'Dr. V. K. Sharma (ICAR PAU)',
  },
  {
    id: 'alert_002',
    title: 'Unseasonal Hailstorm & Thunderstorm Warning',
    crop: 'All Standing Rabi Crops',
    state: 'Gujarat',
    district: 'Anand',
    severity: 'warning',
    message: 'Western disturbance is likely to bring gusty winds (40-50 km/h) and light to moderate hailstorms over the next 48 hours.',
    actionRequired: 'Suspend chemical spraying and heavy irrigation. Ensure farm drainage channels are cleared to prevent waterlogging.',
    broadcastDate: '2026-03-25T07:30:00Z',
    adminName: 'Dr. N. B. Chauhan (AAU)',
  },
];

export const INITIAL_ADMIN_LOGS: AdminActivityLog[] = [
  {
    id: 'log_001',
    adminId: 'user_admin_01',
    adminName: 'Dr. V. K. Sharma',
    action: 'DIAGNOSIS_VERIFIED',
    details: 'Verified Tomato Early Blight scan (#scan_001) for Ramesh Patel. Added scientific notes on Mancozeb dosage.',
    timestamp: '2026-03-20T10:30:00Z',
  },
  {
    id: 'log_002',
    adminId: 'user_admin_01',
    adminName: 'Dr. V. K. Sharma',
    action: 'ALERT_PUBLISHED',
    details: 'Published critical Yellow Stripe Rust alert for Ludhiana & Jalandhar districts.',
    timestamp: '2026-03-24T06:05:00Z',
  },
  {
    id: 'log_003',
    adminId: 'user_admin_01',
    adminName: 'Dr. V. K. Sharma',
    action: 'KVK_UPDATED',
    details: 'Updated contact person and hours for ICAR PAU KVK Center.',
    timestamp: '2026-03-25T09:12:00Z',
  },
];
